//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinderGal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assigne
    {
        public int AssignmentID { get; set; }
        public string Assignment { get; set; }
        public System.DateTime Date_Time { get; set; }
    }
}
